//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capitu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fornecedor
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public int UsuarioId { get; set; }
        public int StatusId { get; set; }
        public int AvatarId { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<double> Altura { get; set; }
        public Nullable<int> Peso { get; set; }
        public Nullable<System.DateTime> DtNascimento { get; set; }
        public string Olhos { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> EnderecoId { get; set; }
        public string Etnia { get; set; }
        public Nullable<int> ImagemAvatarId { get; set; }
        public Nullable<int> ImagemPerfilId { get; set; }
    }
}
